-- ============================
-- TABLES
-- ============================

-- Table: Club
CREATE TABLE club (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    club_logo varchar(50),
    club_invite_id int,
    slug varchar(50) NOT NULL,
    CONSTRAINT club_pk PRIMARY KEY (id)
);

-- Table: Club_invite
CREATE TABLE club_invite (
    id int GENERATED BY DEFAULT AS IDENTITY,
    token varchar(100) NOT NULL,
    created_at timestamp NOT NULL,
    CONSTRAINT club_invite_pk PRIMARY KEY (id)
);

-- Table: Event
CREATE TABLE event (
    id int GENERATED BY DEFAULT AS IDENTITY,
    title varchar(100) NOT NULL,
    description varchar(200) NOT NULL,
    date date NOT NULL,
    start_time time NOT NULL,
    end_time time NULL,
    location varchar(50) NOT NULL,
    event_type_id int NOT NULL,
    club_id int NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT event_pk PRIMARY KEY (id)
);

-- Table: Event_rsvp
CREATE TABLE event_rsvp (
    id int GENERATED BY DEFAULT AS IDENTITY,
    profile_id uuid NOT NULL,
    event_id int NOT NULL,
    status varchar(20) NOT NULL CHECK (status IN ('going', 'not_going', 'maybe')),
    note varchar(500),
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT event_rsvp_pk PRIMARY KEY (id),
    CONSTRAINT event_rsvp_unique_profile_event UNIQUE (profile_id, event_id)
);

-- Table: Forum_post
CREATE TABLE forum_post (
    id int GENERATED BY DEFAULT AS IDENTITY,
    profile_id uuid NOT NULL,
    club_id int NOT NULL,
    category varchar(50) NOT NULL DEFAULT 'general',
    title varchar(50) NOT NULL,
    content text NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT forum_post_pk PRIMARY KEY (id)
);

-- Table: Forum_comment
CREATE TABLE forum_comment (
    id int GENERATED BY DEFAULT AS IDENTITY,
    profile_id uuid NOT NULL,
    content text NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    forum_post_id int NOT NULL,
    CONSTRAINT forum_comment_pk PRIMARY KEY (id)
);

-- Table: Member
CREATE TABLE member (
    id int GENERATED BY DEFAULT AS IDENTITY,
    profile_id uuid NOT NULL,
    club_id int NOT NULL,
    CONSTRAINT member_pk PRIMARY KEY (id)
);

-- Table: Role
CREATE TABLE role (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(10) NOT NULL,
    CONSTRAINT role_pk PRIMARY KEY (id)
);

-- Table: User (profile)
CREATE TABLE profile (
    id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    name varchar(50) NOT NULL,
    email varchar(50) NOT NULL,
    role_id int,
    CONSTRAINT user_pk PRIMARY KEY (id)
);

-- Table: event_type
CREATE TABLE event_type (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    CONSTRAINT event_type_pk PRIMARY KEY (id)
);

-- ============================
-- FOREIGN KEYS
-- ============================

-- Reference: Club_Club_invite (table: club)
ALTER TABLE club ADD CONSTRAINT club_club_invite
    FOREIGN KEY (club_invite_id)
    REFERENCES club_invite (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

-- Reference: Event_Club (table: event)
ALTER TABLE event ADD CONSTRAINT event_club
    FOREIGN KEY (club_id)
    REFERENCES club (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

-- Reference: Event_event_type (table: event)
ALTER TABLE event ADD CONSTRAINT event_event_type
    FOREIGN KEY (event_type_id)
    REFERENCES event_type (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

-- Reference: Event_created_by_Profile (table: event)
ALTER TABLE event ADD CONSTRAINT event_created_by_profile
    FOREIGN KEY (created_by)
    REFERENCES profile (id)
    ON DELETE CASCADE
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

-- Reference: Event_rsvp_Event (table: event_rsvp)
ALTER TABLE event_rsvp ADD CONSTRAINT event_rsvp_event
    FOREIGN KEY (event_id)
    REFERENCES event (id)
    ON DELETE CASCADE
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

-- Reference: Event_rsvp_Profile (table: event_rsvp)
ALTER TABLE event_rsvp ADD CONSTRAINT event_rsvp_profile
    FOREIGN KEY (profile_id)
    REFERENCES profile (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

-- Reference: Forum_comment_Forum_post (table: forum_comment)
ALTER TABLE forum_comment ADD CONSTRAINT forum_comment_forum_post
    FOREIGN KEY (forum_post_id)
    REFERENCES forum_post (id)
    ON DELETE CASCADE
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

-- Reference: Forum_comment_Profile (table: forum_comment)
ALTER TABLE forum_comment ADD CONSTRAINT forum_comment_profile
    FOREIGN KEY (profile_id)
    REFERENCES profile (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

-- Reference: Forum_post_Club (table: forum_post)
ALTER TABLE forum_post ADD CONSTRAINT forum_post_club
    FOREIGN KEY (club_id)
    REFERENCES club (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

-- Reference: Forum_post_Profile (table: forum_post)
ALTER TABLE forum_post ADD CONSTRAINT forum_post_profile
    FOREIGN KEY (profile_id)
    REFERENCES profile (id)
    ON DELETE CASCADE
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

-- Reference: Member_Club (table: member)
ALTER TABLE member ADD CONSTRAINT member_club
    FOREIGN KEY (club_id)
    REFERENCES club (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

-- Reference: Member_Profile (table: member)
ALTER TABLE member ADD CONSTRAINT member_profile
    FOREIGN KEY (profile_id)
    REFERENCES profile (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

-- Reference: Profile_Role (table: profile)
ALTER TABLE profile ADD CONSTRAINT profile_role
    FOREIGN KEY (role_id)
    REFERENCES role (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

-- ============================
-- SEED DATA
-- ============================

-- Seed event types
INSERT INTO event_type (id, name) VALUES
    (1, 'training'),
    (2, 'game'),
    (3, 'analysis'),
    (4, 'other');

-- Ensure identity continues after seeded IDs for event_type
SELECT setval(pg_get_serial_sequence('event_type', 'id'), 4, true);

-- Seed roles
INSERT INTO role (id, name) VALUES
    (1, 'coach'),
    (2, 'player');

-- Ensure identity continues after seeded IDs for role
SELECT setval(pg_get_serial_sequence('role', 'id'), 2, true);

-- ============================
-- FUNCTIONS
-- ============================

-- FUNCTION: get_monthly_attendance
CREATE OR REPLACE FUNCTION public.get_monthly_attendance(
  p_club_id int,
  p_event_type text
)
RETURNS TABLE (
  label text,
  activity int
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    TO_CHAR(e.date, 'Mon') AS label,
    COUNT(r.*)::int AS activity
  FROM event e
  JOIN event_type t ON t.id = e.event_type_id
  LEFT JOIN event_rsvp r
    ON r.event_id = e.id
    AND r.status = 'going'
  WHERE e.club_id = p_club_id
    AND t.name = p_event_type
  GROUP BY 1, EXTRACT(MONTH FROM e.date)
  ORDER BY EXTRACT(MONTH FROM e.date);
END;
$$;

-- End of file.
